apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:9
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    envFrom:
      - secretRef:
        name: book-db-secrets
    volumeMounts:
      - name: libdb
        mountPath: /root/snap/storage
  volumes:
    - name: libdb
      persistentVolumeClaim:
        claimName: mypvc