apiVersion: v1
kind: Secret
metadata:
  name: book-db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: bGlicmFyeQ==
  MYSQL_USER: bHRkZXZvcHM=
  MYSQL_PASSWORD: bHRkZXZvcHM=
